server {
  listen 80;
  root   /var/www;

  location = / {
    try_files /sdklite.js =404;
    add_header Cache-Control "public, max-age=60";
  }

  location = /sdklite.js {
    add_header Cache-Control "public, max-age=60";
  }

  location / {
    return 404;
  }

  # redirect server error pages to the static page /50x.html
  #
  error_page  500 502 503 504  /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }

  # Compression
  # Source: https://github.com/h5bp/server-configs-nginx/blob/main/h5bp/web_performance/compression.conf
  # Doc: https://nginx.org/en/docs/http/ngx_http_gzip_module.html

  # Enable gzip compression.
  gzip on;
  gzip_comp_level 5;

  # Don't compress anything that's already small and unlikely to shrink much
  gzip_min_length 256;

  # Compress data even for clients that are connecting to us via proxies
  gzip_proxied any;

  # Tell proxies to cache both the gzipped and regular version of a resource
  # whenever the client's Accept-Encoding capabilities header varies;
  # Avoids the issue where a non-gzip capable client (which is extremely rare
  # today) would display gibberish if their proxy gave them the gzipped version.
  gzip_vary on;

  # Compress all output labeled with one of the following MIME-types.
  # `text/html` is always compressed by gzip module.
  gzip_types
    application/javascript
    application/json
    application/wasm
    text/css
    text/javascript
    text/plain;
}
